version: '3.8'
services:
  web:
    build: .
    command: gunicorn makemeuppro.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app/
      - static_volume:/app/static/
      - media_volume:/app/media/
      - dbdata:/var/lib/mariadb
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: '${SQL_DATABASE}'
      MYSQL_USER: '${SQL_USER}'
      MYSQL_PASSWORD: '${SQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${SQL_PASSWORD}'
      MARIADB_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}' # .env 파일에서 값을 가져옴
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env


  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - web

volumes:
  dbdata:
  static_volume:
  media_volume:

