# Generated by Django 4.2.8 on 2023-12-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facerecorn",
            fields=[
                ("facerecorn_id", models.AutoField(primary_key=True, serialize=False)),
                ("faceshape_id", models.IntegerField()),
                ("hair_imgpath", models.CharField(max_length=255)),
                ("hair_name", models.CharField(max_length=20)),
                ("hair_content", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "facerecorn",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Faceshape",
            fields=[
                ("faceshape_id", models.AutoField(primary_key=True, serialize=False)),
                ("faceshape_result", models.CharField(max_length=20)),
                ("faceshape_imgpath", models.ImageField(upload_to="faceshapes/")),
                ("faceshape_dt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "faceshape",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Personal",
            fields=[
                ("personal_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "personal_result",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("personal_imgpath", models.ImageField(upload_to="personal/")),
                ("personal_dt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "personal",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Personalrecorn",
            fields=[
                (
                    "personalrecorn_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("personal_id", models.IntegerField()),
                ("cosmetics", models.CharField(max_length=10)),
                ("dyecolor", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "personalrecorn",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Scalp",
            fields=[
                ("scalp_id", models.AutoField(primary_key=True, serialize=False)),
                ("scalp_result", models.CharField(max_length=20)),
                ("scalp_imgpath", models.ImageField(upload_to="scalp/")),
                ("scalp_dt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "scalp",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Scalprecorn",
            fields=[
                ("scalprecorn_id", models.AutoField(primary_key=True, serialize=False)),
                ("scalp_id", models.IntegerField()),
                ("scalprecorn_imgpath", models.CharField(max_length=255)),
                ("scalprecorn_name", models.CharField(max_length=20)),
                ("scalprecorn_content", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "scalprecorn",
                "managed": False,
            },
        ),
    ]
